---
- hosts: xray-cloud
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file)
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Setup xray
      ansible.builtin.import_tasks: tasks/xray-xui.yml
      when: xray_enable 

    - name: Remove Containers
      ansible.builtin.import_tasks: tasks/remove.yml
      when: remove_xray
